FROM --platform=$BUILDPLATFORM golang:1.26.3 AS base
# Needed for ca-certs

FROM scratch
ARG TARGETPLATFORM

COPY --from=base /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
# dockers_v2 stages GoReleaser-built binaries under their target platform.
COPY $TARGETPLATFORM/some-app /some-app

USER 65532:65532
ENTRYPOINT ["/some-app"]
